name: Sealer-Test

on:
  pull_request:
    types: [ labeled ]
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - 'vendor/**'

jobs:
  build:
    name: Test
    runs-on: ubuntu-latest
    env:
      GO111MODULE: on
    steps:
      - name: Set up Go 1.13
        uses: actions/setup-go@v1
        with:
          go-version: 1.13
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: src/github.com/alibaba/sealer

      - name: Install sealer and ginkgo
        shell: bash
        run: |
          source hack/build.sh
          export SEALER_DIR=$THIS_PLATFORM_BIN/sealer/linux_amd64
          echo "$SEALER_DIR" >> $GITHUB_PATH
          go get github.com/onsi/ginkgo/ginkgo
          go get github.com/onsi/gomega/...
          GOPATH=`go env GOPATH`
          export GOPATHBIN=$GOPATH/bin
          echo "$GOPATHBIN" >> $GITHUB_PATH
        working-directory: src/github.com/alibaba/sealer

      - name: Run e2e test
        shell: bash
        working-directory: src/github.com/alibaba/sealer
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
          ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}
          RegionID: ${{ secrets.RegionID }}
        if: ${{ github.event.label.name == 'e2e-test' }}
        run: |
          ginkgo -v test

      - name: Run apply test
        shell: bash
        working-directory: src/github.com/alibaba/sealer
        env:
          REGISTRY_USERNAME: ${{ secrets.REGISTRY_USERNAME }}
          REGISTRY_PASSWORD: ${{ secrets.REGISTRY_PASSWORD }}
          REGISTRY_URL: ${{ secrets.REGISTRY_URL }}
          ACCESSKEYID: ${{ secrets.ACCESSKEYID }}
          ACCESSKEYSECRET: ${{ secrets.ACCESSKEYSECRET }}
          RegionID: ${{ secrets.RegionID }}
        if: ${{ github.event.label.name == 'apply-test' }}
        run: |
          ginkgo -v --focus="sealer apply" test

      - name: Run images test
          shell: bash
          working-directory: src/github.com/alibaba/sealer
          if: ${{ github.event.label.name == 'images-test' }}
          run: |
            ginkgo -v --focus="sealer images" test

      - name: Run inspect test
          shell: bash
          working-directory: src/github.com/alibaba/sealer
          if: ${{ github.event.label.name == 'inspect-test' }}
          run: |
            ginkgo -v --focus="sealer inspect" test

      - name: Run tag test
          shell: bash
          working-directory: src/github.com/alibaba/sealer
          if: ${{ github.event.label.name == 'tag-test' }}
          run: |
            ginkgo -v --focus="sealer tag" test