name: Go

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"
    paths-ignore:
      - 'docs/**'
      - 'vendor/**'
jobs:

  build:
    name: ubuntu - Go v1.14
    runs-on: ubuntu-latest

    steps:

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: '1.14'
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: src/github.com/alibaba/sealer
      - name: Install go ci lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.39.0

      - name: Run Linter
        run: golangci-lint run -v
        working-directory: src/github.com/alibaba/sealer

      - name: Make linux
        shell: bash
        run: |
          readonly platforms=(
            linux/amd64
            linux/arm64
          )

          for platform in "${platforms[@]}"; do
            os=${platform%/*}
            arch=${platform##*/}
            go env -w GOOS="${os}"
            go env -w GOARCH="${arch}"
            make build version=0.0.0
          done
        working-directory: src/github.com/alibaba/sealer

      - name: Save build binaries
        uses: actions/upload-artifact@v2
        with:
          name: sealer-binaries
          path: src/github.com/alibaba/sealer/_output/assets/*.tar.gz*
