name: CI

on:
  push:
    branches: "*"
  pull_request:
    branches: "*"

jobs:

  build:
    name: ${{ matrix.os }} - Go ${{ matrix.go_version }}
    runs-on: ubuntu-latest
    strategy:
      # If you want to matrix build , you can append the following list.
      matrix:
        go_version:
          - 1.13
        os:
          - ubuntu-latest

    steps:

      - name: Set up Go ${{ matrix.go_version }}
        uses: actions/setup-go@v2
        with:
          go-version: ${{ matrix.go_version }}
        id: go

      - name: Check out code into the Go module directory
        uses: actions/checkout@v2
        with:
          ref: ${{ github.ref }}
          path: src/github.com/alibaba/sealer
      - name: Install go ci lint
        run: curl -sSfL https://raw.githubusercontent.com/golangci/golangci-lint/master/install.sh | sh -s -- -b $(go env GOPATH)/bin v1.35.2

#      - name: Run Linter
#        run: golangci-lint run -v
#        working-directory: src/github.com/alibaba/sealer
      - name: Make linux
        shell: bash
        run: |
          readonly platforms=(
            linux/amd64
            linux/arm64
          )

          for platform in "${platforms[@]}"; do
            os=${platform%/*}
            arch=${platform##*/}
            go env -w GOOS="${os}"
            go env -w GOARCH="${arch}"
            make build version=0.0.0
          done
        working-directory: src/github.com/alibaba/sealer

      - name: Save build binaries
        uses: actions/upload-artifact@v2
        with:
          name: sealer-binaries
          path: src/github.com/alibaba/sealer/_output/assets/*.tar.gz*
